replicaCount: 1
image:
  repository: iriscafe50/app_python
  tag: 
service:
  name: app
  namespace:
    create: true
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
  hosts:
    - host: golang-api.local
      paths:
        - /api
resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"