global:
  image:
    tag: "v2.6.6"

controller:
  replicas: 1

server:
  replicas: 1
  service:
    type: LoadBalancer
  extraArgs:
  - --insecure

repoServer:
  replicas: 1

applicationSet:
  replicaCount: 1